### ISSUE TITLE
Change something important

### ISSUE THREAD

**Issue by superfrantv** [Leedotzip/UnityPathFinding#1]
Hello,

i have a wish to you, can you recreate this and remove all Visual things, so there is only the blank pathfinding in this project? I use this for a Tilemap but i need some changes.

my tilemap has a collider, so i can check every tile if it has a collider or not, so i become the not walkable nodes and walkable nodes, but i have no idea how to implement this to your project.

i need a function like 
List<Vector2> GetPath (Vector2 startPos, Vector2 endPos)
 than it checks all tiles from start to endpos and create a path.

thank you, sorry for the bad english iam from germany.
please answer me if you are online here.

**Comment by Leedotzip** [comment]
@superfrantv Message me on discord to discuss this further; Lee#6646
